'use strict'

/**
 * @module UserGroupHelper
 */

const { generateUUID } = require('../../../../app/lib/general.lib.js')
const UserGroupModel = require('../../../../app/models/idm/user-group.model.js')

/**
 * Add a new user group
 *
 * If no `data` is provided, default values will be used. These are
 *
 * - `userId` - 100001
 * - `groupId` - e814fc07-e6e3-4a50-8699-9ede17690674
 *
 * @param {Object} [data] Any data you want to use instead of the defaults used here or in the database
 *
 * @returns {module:GroupModel} The instance of the newly created record
 */
function add (data = {}) {
  const insertData = defaults(data)

  return UserGroupModel.query()
    .insert({ ...insertData })
    .returning('*')
}

/**
 * Returns the defaults used when creating a new record
 *
 * It will override or append to them any data provided. Mainly used by the `add()` method, we make it available
 * for use in tests to avoid having to duplicate values.
 *
 * @param {Object} [data] Any data you want to use instead of the defaults used here or in the database
 */
function defaults (data = {}) {
  const defaults = {
    // We create a random uuid as the id is NOT generated by the db, unlike most other tables
    userGroupId: generateUUID(),
    userId: 100001,
    groupId: 'e814fc07-e6e3-4a50-8699-9ede17690674'
  }

  return {
    ...defaults,
    ...data
  }
}

module.exports = {
  add,
  defaults
}
