'use strict'

/**
 * @module UserRoleHelper
 */

const { randomUUID } = require('crypto')

const UserRoleModel = require('../../../../app/models/idm/user-role.model.js')

/**
 * Add a new user role
 *
 * If no `data` is provided, default values will be used. These are
 *
 * - `userId` - 100001
 * - `roleId` - e814fc07-e6e3-4a50-8699-9ede17690674
 *
 * @param {Object} [data] Any data you want to use instead of the defaults used here or in the database
 *
 * @returns {module:RoleModel} The instance of the newly created record
 */
function add (data = {}) {
  const insertData = defaults(data)

  return UserRoleModel.query()
    .insert({ ...insertData })
    .returning('*')
}

/**
 * Returns the defaults used when creating a new record
 *
 * It will override or append to them any data provided. Mainly used by the `add()` method, we make it available
 * for use in tests to avoid having to duplicate values.
 *
 * @param {Object} [data] Any data you want to use instead of the defaults used here or in the database
 */
function defaults (data = {}) {
  const defaults = {
    // We create a random uuid as the id is NOT generated by the db, unlike most other tables
    userRoleId: randomUUID({ disableEntropyCache: true }),
    userId: 100001,
    roleId: '66b54ff8-edec-417a-8c8b-48d98aad3843'
  }

  return {
    ...defaults,
    ...data
  }
}

module.exports = {
  add,
  defaults
}
