// Things we need to stub
import jwt from 'jsonwebtoken'
import notifyConfig from '../../config/notify.config.js'

// For running our service
import { init } from '../../app/server.js'

const TWENTY_SECONDS_IN_MILLISECONDS = 20000
const THIRTY_SECONDS_IN_MILLISECONDS = 30000

describe('Notify Token Cache plugin', () => {
  let jwtSignSpy
  let server
  let testDate

  beforeEach(async () => {
    jwtSignSpy = vi.spyOn(jwt, 'sign')

    testDate = new Date('2025-08-19T11:03:00.000Z')
    vi.useFakeTimers({ now: testDate })

    // Create server before each test
    server = await init()

    vi.replaceProperty(
      notifyConfig,
      'apiKey',
      'my_test_key-26785a09-ab16-4eb0-8407-a37497a57506-3d844edf-8d35-48ac-975b-e847b4f122b0'
    )
  })

  afterEach(() => {
    vi.useRealTimers()
    vi.restoreAllMocks()
  })

  describe('When called', () => {
    it('returns a signed JSON web token', async () => {
      const result = await server.methods.getNotifyToken()

      expect(result).not.toBeNull()

      const jwtSignFirstCall = jwtSignSpy.mock.calls[0]

      expect(jwtSignFirstCall).toEqual([
        {
          iss: '26785a09-ab16-4eb0-8407-a37497a57506',
          iat: 1755601380
        },
        '3d844edf-8d35-48ac-975b-e847b4f122b0',
        {
          header: { typ: 'JWT', alg: 'HS256' }
        }
      ])
    })
  })

  describe('When called a second time within 25 seconds of the first call', () => {
    it('returns the cached signed JSON web token generated by the first call', async () => {
      const firstCall = await server.methods.getNotifyToken()

      expect(firstCall).not.toBeNull()

      // Jump forwards in time 20 seconds
      vi.advanceTimersByTime(TWENTY_SECONDS_IN_MILLISECONDS)

      const secondCall = await server.methods.getNotifyToken()

      expect(firstCall).toEqual(secondCall)

      expect(jwtSignSpy).toHaveBeenCalledOnce()
    })
  })

  describe('When called a second time more than 25 seconds after the first call', () => {
    it('returns a new JSON web token', async () => {
      const firstCall = await server.methods.getNotifyToken()

      expect(firstCall).not.toBeNull()

      // Jump forwards in time 30 seconds
      vi.advanceTimersByTime(THIRTY_SECONDS_IN_MILLISECONDS)

      const secondCall = await server.methods.getNotifyToken()

      expect(firstCall).not.toEqual(secondCall)

      expect(jwtSignSpy).toHaveBeenCalledTimes(2)
    })
  })
})
