'use strict'

/**
 * @module UserRoleHelper
 */

const { generateUUID } = require('../../../app/lib/general.lib.js')
const { generateUserId } = require('./user.helper.js')
const RoleHelper = require('./role.helper.js')
const UserRoleModel = require('../../../app/models/user-role.model.js')

/**
 * Add a new user role
 *
 * If no `data` is provided, default values will be used. These are
 *
 * - `userId` - [randomly generated - 100001]
 * - `roleId` - [randomly selected UUID from roles]
 *
 * @param {object} [data] - Any data you want to use instead of the defaults used here or in the database
 *
 * @returns {Promise<module:UserRoleModel>} The instance of the newly created record
 */
function add (data = {}) {
  const insertData = defaults(data)

  return UserRoleModel.query()
    .insert({ ...insertData })
    .returning('*')
}

/**
 * Returns the defaults used
 *
 * It will override or append to them any data provided. Mainly used by the `add()` method, we make it available
 * for use in tests to avoid having to duplicate values.
 *
 * @param {object} [data] - Any data you want to use instead of the defaults used here or in the database
 *
 * @returns {object} - Returns the set defaults with the override data spread
 */
function defaults (data = {}) {
  const { id: roleId } = RoleHelper.select()

  const defaults = {
    // We create a random uuid as the id is NOT generated by the db, unlike most other tables
    id: generateUUID(),
    userId: generateUserId(),
    roleId
  }

  return {
    ...defaults,
    ...data
  }
}

module.exports = {
  add,
  defaults
}
